import { describe, it, expect } from 'vitest';
import { findViolations } from '../../scripts/check-pr-hygiene.mjs';

// Table-driven per CLAUDE.md, "Never in public history": every form listed
// there as banned must be caught (positive corpus), and text that merely
// mentions a vendor name — API docs, a model id, the rule's own prose — must
// not (negative corpus). Titles are empty except where the case is about the
// title specifically; each case puts its text in whichever of title/body is
// more natural for that form.

const POSITIVE: Array<[name: string, title: string, body: string]> = [
  [
    'the canonical Claude Code trailer block',
    'fix: retry the module fetch on a transient 5xx',
    [
      'Retries transient failures instead of surfacing them immediately.',
      '',
      '🤖 Generated with [Claude Code](https://claude.com/claude-code)',
      '',
      'Co-Authored-By: Claude <noreply@anthropic.com>',
    ].join('\n'),
  ],
  ['a bare Co-Authored-By trailer', '', 'Co-Authored-By: Claude <noreply@anthropic.com>'],
  [
    'a claude.ai/chat session URL',
    '',
    'See https://claude.ai/chat/abc12345-6789-4def-a123-456789abcdef',
  ],
  [
    'a claude.ai/share session URL',
    '',
    'See https://claude.ai/share/abc12345-6789-4def-a123-456789abcdef',
  ],
  [
    'a claude.com/chat session URL',
    '',
    'See https://claude.com/chat/abc12345-6789-4def-a123-456789abcdef',
  ],
  [
    'a claude.com/share session URL',
    '',
    'See https://claude.com/share/abc12345-6789-4def-a123-456789abcdef',
  ],
  ['a claude-session trailer', '', 'claude-session: abc12345-6789-4def-a123-456789abcdef'],
  [
    'Generated with [Claude Code](...)',
    '',
    'Generated with [Claude Code](https://claude.com/claude-code)',
  ],
  ['Generated by Claude', '', 'Generated by Claude'],
  ['a Copilot co-author trailer', '', 'Co-Authored-By: GitHub Copilot <copilot@github.com>'],
  ['a Cursor co-author trailer', '', 'Co-Authored-By: Cursor <noreply@cursor.sh>'],
  ['a Devin co-author trailer', '', 'Co-Authored-By: Devin AI <devin@cognition.ai>'],
  ['a Gemini co-author trailer', '', 'Co-Authored-By: Gemini <gemini-bot@google.com>'],
  ['an aider co-author trailer', '', 'Co-Authored-By: aider (aider) <aider@aider.chat>'],
  // codex and openai/gpt each pinned alone: the combined-form row this
  // replaced ("OpenAI Codex <codex@openai.com>") names all three at once, so
  // deleting any one of them from VENDORS would leave it green — the other
  // two would still carry the row.
  ['a Codex co-author trailer, alone', '', 'Co-Authored-By: Codex <bot@example.com>'],
  ['an OpenAI co-author trailer, alone', '', 'Co-Authored-By: OpenAI <bot@example.com>'],
  ['a bare gpt co-author trailer', '', 'Co-Authored-By: GPT-4 <bot@example.com>'],
  // Only the loose second alternative (claude.ai/<anything containing
  // session|chat|share>) catches these — the keyword isn't the segment
  // immediately after the domain, so the tighter first alternative misses
  // both on its own.
  ['a claude.ai URL with chat deep in the path', '', 'See https://claude.ai/project/abc/chat'],
  [
    'a claude.ai URL with /session/ deep in the path',
    '',
    'See https://claude.ai/workspace/session/9f8e',
  ],
];

const NEGATIVE: Array<[name: string, title: string, body: string]> = [
  [
    'a body discussing the Claude API',
    'fix: retry the Claude API call on a transient 5xx',
    'Adds a bounded retry around the Claude API client instead of failing on the first transient error.',
  ],
  [
    'a docs body naming the claude-fable model id',
    'docs: list claude-fable in the supported model table',
    'The model table now includes claude-fable-5 alongside the existing entries.',
  ],
  [
    'a plain feat body',
    'feat: add batch export for selected layers',
    'Adds ps_batch_export, which writes every selected layer to its own file in one call.',
  ],
  [
    'the CLAUDE.md rule sentence itself (no vendor follows the colon)',
    '',
    '`Co-Authored-By:` trailers naming a model, "Generated with" lines, and assistant session URLs.',
  ],
  ['a human co-author trailer', '', 'Co-Authored-By: Jane Doe <jane@example.com>'],
  [
    'an Anthropic docs link (not a session URL)',
    '',
    'See https://docs.claude.com/en/docs/agents for the API reference.',
  ],
  [
    'a sentence using "generated" as part of a longer word',
    '',
    'Confirmed by running the fixture: it was regenerated with the build script.',
  ],
];

describe('check-pr-hygiene: findViolations', () => {
  it.each(POSITIVE)('flags %s', (_name, title, body) => {
    expect(findViolations(title, body).length).toBeGreaterThan(0);
  });

  it.each(NEGATIVE)('does not flag %s', (_name, title, body) => {
    expect(findViolations(title, body)).toEqual([]);
  });

  it('reports the source and 1-based line number, never the matched text', () => {
    const findings = findViolations('', 'line one\nCo-Authored-By: Claude <noreply@anthropic.com>');
    expect(findings).toEqual([
      { source: 'body', line: 2, kind: 'a machine co-author trailer' },
      { source: 'body', line: 2, kind: 'an assistant noreply address' },
    ]);
    for (const finding of findings) {
      expect(Object.keys(finding).sort()).toEqual(['kind', 'line', 'source']);
    }
  });

  it('normalizes CRLF before scanning so a Windows-authored body still gets per-line hits', () => {
    const findings = findViolations(
      '',
      'line one\r\nCo-Authored-By: Claude <noreply@anthropic.com>\r\n'
    );
    expect(findings.some((f) => f.line === 2)).toBe(true);
  });

  it('flags a violation in the title, not just the body — deleting the title scan would miss this', () => {
    const findings = findViolations('Co-Authored-By: Claude <noreply@anthropic.com>', '');
    expect(findings).toContainEqual({
      source: 'title',
      line: 1,
      kind: 'a machine co-author trailer',
    });
  });

  it('returns no findings for a null-body PR (title/body both undefined)', () => {
    expect(findViolations(undefined, undefined)).toEqual([]);
  });
});
